//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winAsimilados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archivos
    {
        public int archivoID { get; set; }
        public string archivoNombre { get; set; }
        public string archivoPath { get; set; }
        public byte[] archivoCargado { get; set; }
        public Nullable<System.DateTime> archivoFechaCarga { get; set; }
        public string archivoUsuarioCarga { get; set; }
        public string archivoIDCliente { get; set; }
        public string archivoCliente { get; set; }
        public string archivoIDEmpresa { get; set; }
        public string archivoEmpresa { get; set; }
        public string archivoPeriodo { get; set; }
        public string archivoNominaEmpresaID { get; set; }
        public string archivosURL { get; set; }
    }
}
