//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winAsimilados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificadosDigitales
    {
        public int cerID { get; set; }
        public string cerNombre { get; set; }
        public string cerNum { get; set; }
        public Nullable<System.DateTime> cerFechaVencimiento { get; set; }
        public string cerAsunto { get; set; }
        public string cerPath { get; set; }
        public byte[] cerArchivo { get; set; }
        public string cerKeyNombre { get; set; }
        public string cerKeyPath { get; set; }
        public byte[] cerKeyArchivo { get; set; }
        public string cerNombreEmpresa { get; set; }
        public string cerRFCEmpresa { get; set; }
        public string cerNominaEmpresaID { get; set; }
        public Nullable<System.DateTime> cerFechaCarga { get; set; }
        public string cerUsuarioCarga { get; set; }
    }
}
