//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winAsimilados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogosEmpresas
    {
        public int logoID { get; set; }
        public string logoNombre { get; set; }
        public string logoPath { get; set; }
        public byte[] logoArchivo { get; set; }
        public Nullable<System.DateTime> logoFechaCarga { get; set; }
        public string logousuarioArchivoCarga { get; set; }
        public string logoIDEmpresa { get; set; }
        public string logoEmpresa { get; set; }
    }
}
