using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using C = winAsimilados.Controller;
using E = winAsimilados.Entities;

namespace winAsimilados.Views
{
    public partial class AgregarEmpleado : Form
    {
        string nombre, CURP, RFC, peri;
        C.Controller Controlador = new C.Controller();

        private void lookUpEdit2_EditValueChanged(object sender, EventArgs e)
        {
            //MessageBox.Show("LookUpEdit EditValue = " + (sender as LookUpEdit).EditValue);
            peri = (sender as LookUpEdit).EditValue.ToString();
        }

        public AgregarEmpleado()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void AgregarEmpleado_FormClosed(object sender, FormClosedEventArgs e)
        {
            this.Dispose();
        }

        private void BtnAgregar_Click(object sender, EventArgs e)
        {
            E.Empleado empleado = new E.Empleado();
            nombre = TxtNombreEmpl.Text.ToUpper();
            RFC = TxtRFC.Text.ToUpper();
            CURP = TxtCURP.Text.ToUpper();

            if (nombre == "")
            {
                MessageBox.Show("El campo Nombre no puede estar vacio", "Mensaje", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
            else
            {
                empleado.Nombre = nombre;
            }

            if (RFC == "")
            {
                MessageBox.Show("El campo RFC no puede estar vacio.", "Mensaje", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
            else
            {
                if (!RFC.Length.Equals(13))
                {
                    MessageBox.Show("RFC no cumple con el formato correcto, favor de verificar.", "Mensaje", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
                else
                {
                    empleado.RFC = RFC.ToUpper();
                }
            }

            if (CURP == "")
            {
                MessageBox.Show("El campo CURP no puede estar vacio", "Mensaje", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
            else
            {
                if (!CURP.Length.Equals(18))
                {
                    MessageBox.Show("CURP no cumple con el formato correcto, favor de verificar,", "Mesnaje", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
                else
                {
                    empleado.CURP = CURP.ToUpper();
                }
            }

            if (peri == null)
            {
                MessageBox.Show("Seleccione tipo de periodicidad.", "Mensaje", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            else
            {
                empleado.Periodicidad = peri;
            }

            if (empleado.RFC != null && empleado.Nombre != null && empleado.CURP != null && empleado.Periodicidad != null)
            {
                //MessageBox.Show("Nombre:" + nombre + "\nRFC:" + RFC + "\nCURP:" + CURP + "\nPeriodicidad:" + peri, "mensaje", MessageBoxButtons.OK, MessageBoxIcon.Information);

                if (MessageBox.Show("¿Desea Agregar al empleado?:\n" + empleado.Nombre.ToString() + "\n\nRFC:" + empleado.RFC.ToString() + "\n\nCURP:" + empleado.CURP.ToString() + "\n\nPeriodicidad pago:" + lookUpEdit2.Text + "\n\nFavor de verificar los datos.", "Confirmación", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == System.Windows.Forms.DialogResult.Yes)
                {
                    Controlador.AgregaEmpleado(empleado);
                }
            }
        }
    }
}
