using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using E = winAsimilados.Entities;
using C = winAsimilados.Controller;
using D = soprclscomp;
using DevExpress.XtraEditors;
using V = winAsimilados.Views;

namespace winAsimilados.Views
{
    public partial class EditarUsuario : Form
    {
        E.User user = new E.User();
        C.Controller controller = new C.Controller();
        D.clsSeguridad seguridad = new D.clsSeguridad();
        string bd = C.Conexion.PerformConnection().Database;
        int IDUser;
        bool listadoEmpresas;
        public EditarUsuario(bool listado)
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            listadoEmpresas = listado;
            if (listadoEmpresas.Equals(true))
            {
                C.Conexion.PerformConnection().Open();
            }
        }

        private void GetUser()
        {
            txtNombre.ReadOnly = true;
            txtUsua.ReadOnly = true;
            txtPass.ReadOnly = true;
            txtEstatUsua.ReadOnly = true;
            txtTipoUsua.ReadOnly = true;
            IDUser = Convert.ToInt32(lookUpUsua.EditValue.ToString());
            user = controller.BuscaUsuario(IDUser.ToString());
            txtNombre.Text = user.nombre;
            txtUsua.Text = user.usuario;
            txtPass.Text = user.pass;
            txtTipoUsua.EditValue = user.tipoUsiario;
            txtEstatUsua.EditValue = user.estatusUsuario;
            txtFecReg.Text = user.fecReg.ToString("yyyy-MM-dd");
            if (user.fecMod.ToString("yyyy-MM-dd").Equals("1900-01-01"))
            {
                txtFecMod.Text = "Sin Modificación";
            }
            else
            {
                txtFecMod.Text = user.fecMod.ToString("yyyy-MM-dd");
            }

            layoutControlGroupInfoUser.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Always;
            layoutControlBtnEditar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Always;
        }

        private void EditarUsuario_Load(object sender, EventArgs e)
        {
            layoutControlGroupInfoUser.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
            layoutControlBtnEditar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
            layoutControlBtnAceptar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
            layoutControlBtnCancelar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
        }

        private void lookUpUsua_EditValueChanged(object sender, EventArgs e)
        {
            this.GetUser();
        }

        private void chMostrar_CheckedChanged(object sender, EventArgs e)
        {
            if (chMostrar.Checked.Equals(true))
            {
                txtPass.Properties.UseSystemPasswordChar = false;
            }
            else
            {
                txtPass.Properties.UseSystemPasswordChar = true;
            }
        }

        private void btnEditar_Click(object sender, EventArgs e)
        {
            txtNombre.ReadOnly = false;
            txtUsua.ReadOnly = false;
            txtPass.ReadOnly = false;
            txtEstatUsua.ReadOnly = false;
            txtTipoUsua.ReadOnly = false;
            layoutControlBtnEditar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
            layoutControlBtnAceptar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Always;
            layoutControlBtnCancelar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Always;
        }

        private void btnCancelar_Click(object sender, EventArgs e)
        {
            txtNombre.ReadOnly = true;
            txtUsua.ReadOnly = true;
            txtPass.ReadOnly = true;
            txtEstatUsua.ReadOnly = true;
            txtTipoUsua.ReadOnly = true;
            layoutControlBtnEditar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Always;
            layoutControlBtnAceptar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
            layoutControlBtnCancelar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
        }

        private void btnAceptar_Click(object sender, EventArgs e)
        {
            user.nombre = txtNombre.Text;
            user.usuario = txtUsua.Text;
            string passEncrip = seguridad.EncryptString(txtPass.Text);
            user.pass = passEncrip;
            user.tipoUsiario = txtTipoUsua.EditValue.ToString();
            user.estatusUsuario = txtEstatUsua.EditValue.ToString();
            user.fecMod = System.DateTime.Today;

            var result = XtraMessageBox.Show("¿Está seguro de modificar la información del usuario?"
                , "Confirmación", MessageBoxButtons.YesNo, MessageBoxIcon.Question);

            if (result.Equals(DialogResult.Yes))
            {
                //XtraMessageBox.Show("Entra a modificar");
                if(controller.EditaUsuario(user, bd).Equals(true))
                {
                    XtraMessageBox.Show("¡Información de Usuario Actualizada!",
                        "Mensaje", MessageBoxButtons.OK, MessageBoxIcon.Information);

                    this.GetUser();
                }
            }
            else
            {
                this.GetUser();
            }
        }

        private void EditarUsuario_FormClosed(object sender, FormClosedEventArgs e)
        {
            if (listadoEmpresas.Equals(true))
            {
                V.ListaEmpresas listaEmpresas = new V.ListaEmpresas();
                listaEmpresas.Show();
            }
            else
            {
                this.Dispose();
            }
        }
    }
}
