using DevExpress.XtraEditors;
using DevExpress.XtraSplashScreen;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using C = winAsimilados.Controller;
using E = winAsimilados.Entities;

namespace winAsimilados.Views
{
    public partial class EmpresasPagoAsimilados : Form
    {
        C.Controller controlador = new C.Controller();
        E.EmpresaPago empresaPago = new E.EmpresaPago();
        SplashScreenManager splash;
        string ID;
        string newID;
        int numID, IDE;
        string IDEmp, RFC, RS, Estatus;
        public EmpresasPagoAsimilados(SplashScreenManager splashScreenManager)
        {
            splash = splashScreenManager;
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }
        private void GetNextID()
        {
            ID = controlador.GetIDEmpresaPago();

            for (int i = 0; i < ID.Length; i++)
            {
                if (Char.IsDigit(ID[i]))
                {
                    newID += ID[i];
                }
            }
            if (newID.Length > 0)
            {
                numID = int.Parse(newID);
            }

            if (numID.ToString().Length.Equals(1))
            {
                numID++;
                newID = "I00" + numID.ToString();
            }else if (numID.ToString().Length.Equals(2))
            {
                numID++;
                newID = "I0" + numID.ToString();
            }
            else if (numID.ToString().Length.Equals(3))
            {
                numID++;
                newID = "I" + numID.ToString();
            }

                //txtID.Text = newID;
                txtID.Text = newID;
            //cliente.ID = newID;
            newID = "";
        }

        public void LlenaTabla()
        {
            controlador.ListaEmpresasPago(gridControlEmpr);
            gridControlEmpr.Visible = true;
        }

        private void EmpresasPagoAsimilados_Load(object sender, EventArgs e)
        {
            this.GetNextID();
            this.LlenaTabla();
            if (splash.IsSplashFormVisible.Equals(true))
            {
                splash.CloseWaitForm();
            }
        }

        private void btnBaja_Click(object sender, EventArgs e)
        {
            for (int i = 0; i < gridViewEmpr.RowCount; i++)
            {
                if (gridViewEmpr.IsRowSelected(i))
                {
                    IDE = Convert.ToInt32(gridViewEmpr.GetRowCellValue(i, gridViewEmpr.Columns[0]).ToString());
                    IDEmp = gridViewEmpr.GetRowCellValue(i, gridViewEmpr.Columns[1]).ToString();
                    RFC = gridViewEmpr.GetRowCellValue(i, gridViewEmpr.Columns[2]).ToString();
                    RS = gridViewEmpr.GetRowCellValue(i, gridViewEmpr.Columns[3]).ToString();
                    Estatus = gridViewEmpr.GetRowCellValue(i, gridViewEmpr.Columns[4]).ToString();
                }
            }
            if (Estatus.Equals("A"))
            {
                if (controlador.BajaEmpresaPago(IDE).Equals(true))
                {

                    XtraMessageBox.Show("!La Empresa: " + RS + " fue dada de baja con éxito¡", "Mensaje", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    layoutControlbtnEditar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Always;
                    layoutControlbtnGuardar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                    layoutControlbtnCancelar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                    layoutControlbtnBaja.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                    layoutControlbtnAlta.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                    gridColumnRazonSocial.OptionsColumn.AllowEdit = false;
                    gridColumnRFC.OptionsColumn.AllowEdit = false;
                    gridColumnEstatus.OptionsColumn.AllowEdit = false;
                    this.LlenaTabla();
                }
                else
                {
                    XtraMessageBox.Show("!Error al dar de baja la empresa:" + RS + " ¡", "Mensaje", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    layoutControlbtnEditar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Always;
                    layoutControlbtnGuardar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                    layoutControlbtnCancelar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                    layoutControlbtnBaja.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                    layoutControlbtnAlta.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                    gridColumnRazonSocial.OptionsColumn.AllowEdit = false;
                    gridColumnRFC.OptionsColumn.AllowEdit = false;
                    gridColumnEstatus.OptionsColumn.AllowEdit = false;
                    this.LlenaTabla();
                }
            }
            else
            {
                XtraMessageBox.Show("!La Empresa: " + RS + " Ya fue dada de baja anteriormente¡", "Mensaje", MessageBoxButtons.OK, MessageBoxIcon.Information);
                layoutControlbtnEditar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Always;
                layoutControlbtnGuardar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                layoutControlbtnCancelar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                layoutControlbtnBaja.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                layoutControlbtnAlta.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                gridColumnRazonSocial.OptionsColumn.AllowEdit = false;
                gridColumnRFC.OptionsColumn.AllowEdit = false;
                gridColumnEstatus.OptionsColumn.AllowEdit = false;
                this.LlenaTabla();
            }
        }

        private void btnAltaEmpr_Click(object sender, EventArgs e)
        {
            for (int i = 0; i < gridViewEmpr.RowCount; i++)
            {
                if (gridViewEmpr.IsRowSelected(i))
                {
                    IDE = Convert.ToInt32(gridViewEmpr.GetRowCellValue(i, gridViewEmpr.Columns[0]).ToString());
                    IDEmp = gridViewEmpr.GetRowCellValue(i, gridViewEmpr.Columns[1]).ToString();
                    RFC = gridViewEmpr.GetRowCellValue(i, gridViewEmpr.Columns[2]).ToString();
                    RS = gridViewEmpr.GetRowCellValue(i, gridViewEmpr.Columns[3]).ToString();
                    Estatus = gridViewEmpr.GetRowCellValue(i, gridViewEmpr.Columns[4]).ToString();
                }
            }
            if (Estatus.Equals("I"))
            {
                if (controlador.AltaEmpresaPago(IDE).Equals(true))
                {

                    XtraMessageBox.Show("!La Empresa: " + RS + " fue dada de alta con éxito¡", "Mensaje", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    layoutControlbtnEditar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Always;
                    layoutControlbtnGuardar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                    layoutControlbtnCancelar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                    layoutControlbtnBaja.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                    layoutControlbtnAlta.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                    gridColumnRazonSocial.OptionsColumn.AllowEdit = false;
                    gridColumnRFC.OptionsColumn.AllowEdit = false;
                    gridColumnEstatus.OptionsColumn.AllowEdit = false;
                    this.LlenaTabla();
                }
                else
                {
                    XtraMessageBox.Show("!Error al dar de alta la empresa:" + RS + " ¡", "Mensaje", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    layoutControlbtnEditar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Always;
                    layoutControlbtnGuardar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                    layoutControlbtnCancelar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                    layoutControlbtnBaja.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                    layoutControlbtnAlta.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                    gridColumnRazonSocial.OptionsColumn.AllowEdit = false;
                    gridColumnRFC.OptionsColumn.AllowEdit = false;
                    gridColumnEstatus.OptionsColumn.AllowEdit = false;
                    this.LlenaTabla();
                }
            }
            else
            {
                XtraMessageBox.Show("!La Empresa: " + RS + " Ya fue dada de alta anteriormente¡", "Mensaje", MessageBoxButtons.OK, MessageBoxIcon.Information);
                layoutControlbtnEditar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Always;
                layoutControlbtnGuardar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                layoutControlbtnCancelar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                layoutControlbtnBaja.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                layoutControlbtnAlta.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                gridColumnRazonSocial.OptionsColumn.AllowEdit = false;
                gridColumnRFC.OptionsColumn.AllowEdit = false;
                gridColumnEstatus.OptionsColumn.AllowEdit = false;
                this.LlenaTabla();
            }
        }

        private void btnEditar_Click(object sender, EventArgs e)
        {
            layoutControlbtnEditar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
            layoutControlbtnGuardar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Always;
            layoutControlbtnCancelar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Always;
            layoutControlbtnBaja.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Always;
            layoutControlbtnAlta.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Always;
            gridColumnRazonSocial.OptionsColumn.AllowEdit = true;
            gridColumnRFC.OptionsColumn.AllowEdit = true;
            gridColumnEstatus.OptionsColumn.AllowEdit = true;
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            #region validaciones
            if (txtRazon.Text.Equals(""))
            {
                XtraMessageBox.Show("Por favor, ingrese Razon Social", "Mensaje", MessageBoxButtons.OK, MessageBoxIcon.Information);
                return;
            }
            else
            {
                empresaPago.RazonSocial = txtRazon.Text;
            }

            if (txtRFC.Text.Equals(""))
            {
                XtraMessageBox.Show("Por favor, ingrese RFC", "Mensaje", MessageBoxButtons.OK, MessageBoxIcon.Information);
                return;
            }
            else
            {
                empresaPago.RFC = txtRFC.Text;
            }
            #endregion
            empresaPago.IDEmpresa = txtID.Text;

            if (controlador.InsertaEmpresaPago(empresaPago).Equals(true))
            {
                this.LlenaTabla();
                this.GetNextID();
                txtRazon.Text = "";
                txtRFC.Text = "";
            }
            else
            {
                XtraMessageBox.Show("Error al dar de alta Empresa.", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void btnCancelar_Click(object sender, EventArgs e)
        {
            layoutControlbtnEditar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Always;
            layoutControlbtnGuardar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
            layoutControlbtnCancelar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
            layoutControlbtnBaja.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
            layoutControlbtnAlta.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
            gridColumnRazonSocial.OptionsColumn.AllowEdit = false;
            gridColumnRFC.OptionsColumn.AllowEdit = false;
            gridColumnEstatus.OptionsColumn.AllowEdit = false;
            this.LlenaTabla();
        }

        private void btnGuardar_Click(object sender, EventArgs e)
        {
            var respuesta = XtraMessageBox.Show("¿Desea guardar los cambios realizados?", "Confirmación", MessageBoxButtons.YesNo, MessageBoxIcon.Question);

            if (respuesta.Equals(DialogResult.Yes))
            {
                var listaEmpresa = new List<E.EmpresaPago>();
                for (int i = 0; i < gridViewEmpr.RowCount; i++)
                {
                    IDE = Convert.ToInt32(gridViewEmpr.GetRowCellValue(i, gridViewEmpr.Columns[0]).ToString());
                    IDEmp = gridViewEmpr.GetRowCellValue(i, gridViewEmpr.Columns[1]).ToString();
                    RFC = gridViewEmpr.GetRowCellValue(i, gridViewEmpr.Columns[2]).ToString();
                    RS = gridViewEmpr.GetRowCellValue(i, gridViewEmpr.Columns[3]).ToString();
                    Estatus = gridViewEmpr.GetRowCellValue(i, gridViewEmpr.Columns[4]).ToString();
                    listaEmpresa.Add(new E.EmpresaPago
                    {
                        ID = IDE,
                        IDEmpresa = IDEmp,
                        RFC = RFC,
                        RazonSocial = RS,
                        Estatus = Estatus
                    });
                }

                if (controlador.ModificaEmpresaPago(listaEmpresa).Equals(true))
                {
                    XtraMessageBox.Show("!Información actualizada¡", "Mensaje", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    layoutControlbtnEditar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Always;
                    layoutControlbtnGuardar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                    layoutControlbtnCancelar.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                    layoutControlbtnBaja.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                    layoutControlbtnAlta.Visibility = DevExpress.XtraLayout.Utils.LayoutVisibility.Never;
                    gridColumnRazonSocial.OptionsColumn.AllowEdit = false;
                    gridColumnRFC.OptionsColumn.AllowEdit = false;
                    gridColumnEstatus.OptionsColumn.AllowEdit = false;
                    this.LlenaTabla();
                }

            }
        }
    }
}
